    name = "421418741"  # 替换为你的 Worker 名称
    main = "/page/index.html"  # 假设你的 Worker 入口文件是 src/index.js，可以根据实际情况修改
    compatibility_date = "2024-01-01"  # 指定兼容性日期
    
    [vars]
    # 你可以在这里添加环境变量，例如：
    # WEBSITE_BUCKET = "your-bucket-name" 
    
    [build]
      command = "npm run build" # 如果需要构建静态文件，添加构建命令
      #  dir = "public" # 如果静态文件在 public 目录下
      #  [build.upload]
      #    format = "service-worker" # 可选，如果你的 worker 需要 service worker 的能力
    
    [site]
      bucket = "./public" # 静态文件目录
      entry-point = "workers-site" # 静态文件入口点
      include = ["**/*"] # 包含所有文件
      exclude = []       # 不排除任何文件
    
    # 如果使用单页应用 (SPA)，可能需要配置路由
    # [[routes]]
    # pattern = "/"
    # custom_domain = true